service: html-to-pdf-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 1024
  timeout: 30
  environment:
    AWS_BUCKET_NAME: "mario121buckett"
    AWS_BUCKET_REGION: "ap-south-1"

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::mario121buckett/*"

functions:
  convertHtmlToPdf:
    handler: handler.main
    events:
      - http:
          path: convert
          method: post

